AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Resources:
  GuardDutyInvitation:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 60

  slackeventguardduty:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: slack.handler
      Runtime: nodejs8.10
      Timeout: 60
      Environment:
        Variables:
          slackchannel: "test-room"
          slackurl: "https://hooks.slack.com"

